//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Master_Pol
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerSaleHistory
    {
        public int ID { get; set; }
        public int PartnerID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal ProductCount { get; set; }
    
        public virtual Partner Partner { get; set; }
    }
}
